name: Health check
on:
  workflow_dispatch:
jobs:
  health:
    runs-on: ubuntu-22.04
    steps:
      - name: Check deployed site health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://lnxbusdrvr-full-stack-open-pokedex.onrender.com/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s

#      - name: Inform to Discord
#        if: failure()
#        uses: Ilshidur/discord-webhook-action@master
#        with:
#          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
#          message: |
#            ❌ Health check failed!
#            URL: https://lnxbusdrvr-full-stack-open-pokedex.onrender.com/
#            Time: ${{ github.event.schedule }}
        
          
